# Generated by Django 5.2.5 on 2025-09-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
    ]
